// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xuart_config_register.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XUart_config_register_CfgInitialize(XUart_config_register *InstancePtr, XUart_config_register_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

u32 XUart_config_register_Get_a_BaseAddress(XUart_config_register *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE);
}

u32 XUart_config_register_Get_a_HighAddress(XUart_config_register *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XUART_CONFIG_REGISTER_AXILITES_ADDR_A_HIGH);
}

u32 XUart_config_register_Get_a_TotalBytes(XUart_config_register *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XUART_CONFIG_REGISTER_AXILITES_ADDR_A_HIGH - XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE + 1);
}

u32 XUart_config_register_Get_a_BitWidth(XUart_config_register *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUART_CONFIG_REGISTER_AXILITES_WIDTH_A;
}

u32 XUart_config_register_Get_a_Depth(XUart_config_register *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XUART_CONFIG_REGISTER_AXILITES_DEPTH_A;
}

u32 XUart_config_register_Write_a_Words(XUart_config_register *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUART_CONFIG_REGISTER_AXILITES_ADDR_A_HIGH - XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XUart_config_register_Read_a_Words(XUart_config_register *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XUART_CONFIG_REGISTER_AXILITES_ADDR_A_HIGH - XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE + (offset + i)*4);
    }
    return length;
}

u32 XUart_config_register_Write_a_Bytes(XUart_config_register *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUART_CONFIG_REGISTER_AXILITES_ADDR_A_HIGH - XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XUart_config_register_Read_a_Bytes(XUart_config_register *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XUART_CONFIG_REGISTER_AXILITES_ADDR_A_HIGH - XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE + offset + i);
    }
    return length;
}

