// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xuart_config_register.h"

extern XUart_config_register_Config XUart_config_register_ConfigTable[];

XUart_config_register_Config *XUart_config_register_LookupConfig(u16 DeviceId) {
	XUart_config_register_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XUART_CONFIG_REGISTER_NUM_INSTANCES; Index++) {
		if (XUart_config_register_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XUart_config_register_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XUart_config_register_Initialize(XUart_config_register *InstancePtr, u16 DeviceId) {
	XUart_config_register_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XUart_config_register_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XUart_config_register_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

