// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xall_data_sender.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAll_data_sender_CfgInitialize(XAll_data_sender *InstancePtr, XAll_data_sender_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

u32 XAll_data_sender_Get_a_BaseAddress(XAll_data_sender *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XALL_DATA_SENDER_AXILITES_ADDR_A_BASE);
}

u32 XAll_data_sender_Get_a_HighAddress(XAll_data_sender *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XALL_DATA_SENDER_AXILITES_ADDR_A_HIGH);
}

u32 XAll_data_sender_Get_a_TotalBytes(XAll_data_sender *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XALL_DATA_SENDER_AXILITES_ADDR_A_HIGH - XALL_DATA_SENDER_AXILITES_ADDR_A_BASE + 1);
}

u32 XAll_data_sender_Get_a_BitWidth(XAll_data_sender *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XALL_DATA_SENDER_AXILITES_WIDTH_A;
}

u32 XAll_data_sender_Get_a_Depth(XAll_data_sender *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XALL_DATA_SENDER_AXILITES_DEPTH_A;
}

u32 XAll_data_sender_Write_a_Words(XAll_data_sender *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XALL_DATA_SENDER_AXILITES_ADDR_A_HIGH - XALL_DATA_SENDER_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XALL_DATA_SENDER_AXILITES_ADDR_A_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XAll_data_sender_Read_a_Words(XAll_data_sender *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XALL_DATA_SENDER_AXILITES_ADDR_A_HIGH - XALL_DATA_SENDER_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XALL_DATA_SENDER_AXILITES_ADDR_A_BASE + (offset + i)*4);
    }
    return length;
}

u32 XAll_data_sender_Write_a_Bytes(XAll_data_sender *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XALL_DATA_SENDER_AXILITES_ADDR_A_HIGH - XALL_DATA_SENDER_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XALL_DATA_SENDER_AXILITES_ADDR_A_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XAll_data_sender_Read_a_Bytes(XAll_data_sender *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XALL_DATA_SENDER_AXILITES_ADDR_A_HIGH - XALL_DATA_SENDER_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XALL_DATA_SENDER_AXILITES_ADDR_A_BASE + offset + i);
    }
    return length;
}

