# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/UARTConfig.xdc

# Block Designs: bd/Uart_ETH/Uart_ETH.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH || ORIG_REF_NAME==Uart_ETH}]

# IP: bd/Uart_ETH/ip/Uart_ETH_processing_system7_0_1/Uart_ETH_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_processing_system7_0_1 || ORIG_REF_NAME==Uart_ETH_processing_system7_0_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_axi_gpio_LED_0/Uart_ETH_axi_gpio_LED_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_axi_gpio_LED_0 || ORIG_REF_NAME==Uart_ETH_axi_gpio_LED_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_axi_gpio_SW_0/Uart_ETH_axi_gpio_SW_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_axi_gpio_SW_0 || ORIG_REF_NAME==Uart_ETH_axi_gpio_SW_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_ps7_0_axi_periph_0/Uart_ETH_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_ps7_0_axi_periph_0 || ORIG_REF_NAME==Uart_ETH_ps7_0_axi_periph_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xbar_0/Uart_ETH_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xbar_0 || ORIG_REF_NAME==Uart_ETH_xbar_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_AllDataMover_0_0/Uart_ETH_AllDataMover_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_AllDataMover_0_0 || ORIG_REF_NAME==Uart_ETH_AllDataMover_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_smartconnect_0_0/Uart_ETH_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_smartconnect_0_0 || ORIG_REF_NAME==Uart_ETH_smartconnect_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_All_Data_Sender_0_4/Uart_ETH_All_Data_Sender_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_All_Data_Sender_0_4 || ORIG_REF_NAME==Uart_ETH_All_Data_Sender_0_4}]

# IP: bd/Uart_ETH/ip/Uart_ETH_clk_wiz_0_0/Uart_ETH_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_clk_wiz_0_0 || ORIG_REF_NAME==Uart_ETH_clk_wiz_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_clk_wiz_1_0/Uart_ETH_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_clk_wiz_1_0 || ORIG_REF_NAME==Uart_ETH_clk_wiz_1_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_0/Uart_ETH_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_0 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_rst_ps7_0_100M_1/Uart_ETH_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_rst_ps7_0_100M_1 || ORIG_REF_NAME==Uart_ETH_rst_ps7_0_100M_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_rst_ps7_0_100M_2/Uart_ETH_rst_ps7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_rst_ps7_0_100M_2 || ORIG_REF_NAME==Uart_ETH_rst_ps7_0_100M_2}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_Config_Register_0_0/Uart_ETH_UART_Config_Register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_Config_Register_0_0 || ORIG_REF_NAME==Uart_ETH_UART_Config_Register_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_Extract_UART_Features_0_0/Uart_ETH_Extract_UART_Features_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_Extract_UART_Features_0_0 || ORIG_REF_NAME==Uart_ETH_Extract_UART_Features_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_2/Uart_ETH_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_2 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_2}]

# IP: bd/Uart_ETH/ip/Uart_ETH_baudrate_gen_0_0/Uart_ETH_baudrate_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_baudrate_gen_0_0 || ORIG_REF_NAME==Uart_ETH_baudrate_gen_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_1_14/Uart_ETH_util_vector_logic_1_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_1_14 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_1_14}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_10_0/Uart_ETH_DataMuxOut4Bit_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_10_0 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_10_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_0_3/Uart_ETH_DataMuxOut4Bit_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_0_3 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_0_3}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_0/Uart_ETH_DataMuxOut4Bit_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_0 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_1/Uart_ETH_DataMuxOut4Bit_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_1 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_2/Uart_ETH_DataMuxOut4Bit_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_2 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_2}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_3/Uart_ETH_DataMuxOut4Bit_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_3 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_3}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_4/Uart_ETH_DataMuxOut4Bit_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_4 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_4}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_5/Uart_ETH_DataMuxOut4Bit_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_5 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_5}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_6/Uart_ETH_DataMuxOut4Bit_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_6 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_6}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_7/Uart_ETH_DataMuxOut4Bit_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_7 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_7}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_8/Uart_ETH_DataMuxOut4Bit_1_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_8 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_8}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_9/Uart_ETH_DataMuxOut4Bit_1_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_9 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_9}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_10/Uart_ETH_DataMuxOut4Bit_1_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_10 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_10}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_11/Uart_ETH_DataMuxOut4Bit_1_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_11 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_11}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_12/Uart_ETH_DataMuxOut4Bit_1_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_12 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_12}]

# IP: bd/Uart_ETH/ip/Uart_ETH_DataMuxOut4Bit_1_13/Uart_ETH_DataMuxOut4Bit_1_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_DataMuxOut4Bit_1_13 || ORIG_REF_NAME==Uart_ETH_DataMuxOut4Bit_1_13}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_4/Uart_ETH_util_vector_logic_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_4 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_4}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_15/Uart_ETH_fifo_generator_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_15 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_15}]

# IP: bd/Uart_ETH/ip/Uart_ETH_PISO_0_0/Uart_ETH_PISO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_PISO_0_0 || ORIG_REF_NAME==Uart_ETH_PISO_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_LED_Tester_0_0/Uart_ETH_LED_Tester_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_LED_Tester_0_0 || ORIG_REF_NAME==Uart_ETH_LED_Tester_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_14/Uart_ETH_util_vector_logic_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_14 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_14}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlconcat_0_0/Uart_ETH_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlconcat_0_0 || ORIG_REF_NAME==Uart_ETH_xlconcat_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_Register_8_Input_0_0/Uart_ETH_Register_8_Input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_Register_8_Input_0_0 || ORIG_REF_NAME==Uart_ETH_Register_8_Input_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_Register_8_Input_1_0/Uart_ETH_Register_8_Input_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_Register_8_Input_1_0 || ORIG_REF_NAME==Uart_ETH_Register_8_Input_1_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_Register_8_Input_Rx1_0/Uart_ETH_Register_8_Input_Rx1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_Register_8_Input_Rx1_0 || ORIG_REF_NAME==Uart_ETH_Register_8_Input_Rx1_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_Register_8_Input_Rx2_0/Uart_ETH_Register_8_Input_Rx2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_Register_8_Input_Rx2_0 || ORIG_REF_NAME==Uart_ETH_Register_8_Input_Rx2_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_LED_Sample_0_0/Uart_ETH_LED_Sample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_LED_Sample_0_0 || ORIG_REF_NAME==Uart_ETH_LED_Sample_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_LED_Sample_0_1/Uart_ETH_LED_Sample_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_LED_Sample_0_1 || ORIG_REF_NAME==Uart_ETH_LED_Sample_0_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_LED_Sample_1_0/Uart_ETH_LED_Sample_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_LED_Sample_1_0 || ORIG_REF_NAME==Uart_ETH_LED_Sample_1_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_LED_Sample_1_1/Uart_ETH_LED_Sample_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_LED_Sample_1_1 || ORIG_REF_NAME==Uart_ETH_LED_Sample_1_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_Tick_Timer_General_0_0/Uart_ETH_Tick_Timer_General_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_Tick_Timer_General_0_0 || ORIG_REF_NAME==Uart_ETH_Tick_Timer_General_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_0_0/Uart_ETH_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_0_0 || ORIG_REF_NAME==Uart_ETH_xlslice_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_0_1/Uart_ETH_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_0_1 || ORIG_REF_NAME==Uart_ETH_xlslice_0_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_KeyPad_0/Uart_ETH_xlslice_KeyPad_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_KeyPad_0 || ORIG_REF_NAME==Uart_ETH_xlslice_KeyPad_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_Tick_Timer_General_0_1/Uart_ETH_Tick_Timer_General_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_Tick_Timer_General_0_1 || ORIG_REF_NAME==Uart_ETH_Tick_Timer_General_0_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_LCD_0/Uart_ETH_xlslice_LCD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_LCD_0 || ORIG_REF_NAME==Uart_ETH_xlslice_LCD_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_LCD1_2/Uart_ETH_xlslice_LCD1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_LCD1_2 || ORIG_REF_NAME==Uart_ETH_xlslice_LCD1_2}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_LCD_RS_0/Uart_ETH_xlslice_LCD_RS_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_LCD_RS_0 || ORIG_REF_NAME==Uart_ETH_xlslice_LCD_RS_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_LCD1_0/Uart_ETH_xlslice_LCD1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_LCD1_0 || ORIG_REF_NAME==Uart_ETH_xlslice_LCD1_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_LCD_RS_2/Uart_ETH_xlslice_LCD_RS_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_LCD_RS_2 || ORIG_REF_NAME==Uart_ETH_xlslice_LCD_RS_2}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_LCD_RS_1/Uart_ETH_xlslice_LCD_RS_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_LCD_RS_1 || ORIG_REF_NAME==Uart_ETH_xlslice_LCD_RS_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_LCD1_1/Uart_ETH_xlslice_LCD1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_LCD1_1 || ORIG_REF_NAME==Uart_ETH_xlslice_LCD1_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_Counter_0_0/Uart_ETH_Counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_Counter_0_0 || ORIG_REF_NAME==Uart_ETH_Counter_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlconstant_0_0/Uart_ETH_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlconstant_0_0 || ORIG_REF_NAME==Uart_ETH_xlconstant_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_18/Uart_ETH_util_vector_logic_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_18 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_18}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlconcat_0_1/Uart_ETH_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlconcat_0_1 || ORIG_REF_NAME==Uart_ETH_xlconcat_0_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlconstant_0_1/Uart_ETH_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlconstant_0_1 || ORIG_REF_NAME==Uart_ETH_xlconstant_0_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_LCD_RW_0/Uart_ETH_xlslice_LCD_RW_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_LCD_RW_0 || ORIG_REF_NAME==Uart_ETH_xlslice_LCD_RW_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_19/Uart_ETH_util_vector_logic_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_19 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_19}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_20/Uart_ETH_util_vector_logic_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_20 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_20}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_21/Uart_ETH_util_vector_logic_0_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_21 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_21}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_22/Uart_ETH_util_vector_logic_0_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_22 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_22}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_23/Uart_ETH_util_vector_logic_0_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_23 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_23}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_24/Uart_ETH_util_vector_logic_0_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_24 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_24}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_25/Uart_ETH_util_vector_logic_0_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_25 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_25}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_26/Uart_ETH_util_vector_logic_0_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_26 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_26}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_27/Uart_ETH_util_vector_logic_0_27.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_27 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_27}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_28/Uart_ETH_util_vector_logic_0_28.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_28 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_28}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_29/Uart_ETH_util_vector_logic_0_29.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_29 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_29}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_30/Uart_ETH_util_vector_logic_0_30.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_30 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_30}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_11_0/Uart_ETH_util_vector_logic_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_11_0 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_11_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_11_1/Uart_ETH_util_vector_logic_11_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_11_1 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_11_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_12_0/Uart_ETH_util_vector_logic_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_12_0 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_12_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_12_1/Uart_ETH_util_vector_logic_12_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_12_1 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_12_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_12_2/Uart_ETH_util_vector_logic_12_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_12_2 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_12_2}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_12_3/Uart_ETH_util_vector_logic_12_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_12_3 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_12_3}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_12_4/Uart_ETH_util_vector_logic_12_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_12_4 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_12_4}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_12_5/Uart_ETH_util_vector_logic_12_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_12_5 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_12_5}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_12_6/Uart_ETH_util_vector_logic_12_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_12_6 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_12_6}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_12_7/Uart_ETH_util_vector_logic_12_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_12_7 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_12_7}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_21_0/Uart_ETH_util_vector_logic_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_21_0 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_21_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_21_1/Uart_ETH_util_vector_logic_21_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_21_1 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_21_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_21_2/Uart_ETH_util_vector_logic_21_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_21_2 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_21_2}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_21_3/Uart_ETH_util_vector_logic_21_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_21_3 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_21_3}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_21_4/Uart_ETH_util_vector_logic_21_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_21_4 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_21_4}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_21_5/Uart_ETH_util_vector_logic_21_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_21_5 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_21_5}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_21_6/Uart_ETH_util_vector_logic_21_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_21_6 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_21_6}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_21_7/Uart_ETH_util_vector_logic_21_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_21_7 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_21_7}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_21_8/Uart_ETH_util_vector_logic_21_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_21_8 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_21_8}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_30_0/Uart_ETH_util_vector_logic_30_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_30_0 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_30_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_37/Uart_ETH_util_vector_logic_0_37.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_37 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_37}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_3/Uart_ETH_fifo_generator_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_3 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_3}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Without_Baud_1_17/Uart_ETH_UART_RX_Without_Baud_1_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Without_Baud_1_17 || ORIG_REF_NAME==Uart_ETH_UART_RX_Without_Baud_1_17}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_14_0/Uart_ETH_util_vector_logic_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_14_0 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_14_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Without_Baud_14_0/Uart_ETH_UART_TX_Without_Baud_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Without_Baud_14_0 || ORIG_REF_NAME==Uart_ETH_UART_TX_Without_Baud_14_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_0/Uart_ETH_UART_TX_Extended_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_0 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_0/Uart_ETH_UART_RX_Extended_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_0 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_5/Uart_ETH_util_vector_logic_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_5 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_5}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_4/Uart_ETH_UART_TX_Extended_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_4 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_4}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_36/Uart_ETH_util_vector_logic_0_36.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_36 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_36}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_5/Uart_ETH_fifo_generator_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_5 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_5}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_4/Uart_ETH_UART_RX_Extended_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_4 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_4}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_6/Uart_ETH_util_vector_logic_2_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_6 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_6}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_5/Uart_ETH_UART_TX_Extended_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_5 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_5}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_38/Uart_ETH_util_vector_logic_0_38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_38 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_38}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_6/Uart_ETH_fifo_generator_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_6 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_6}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_5/Uart_ETH_UART_RX_Extended_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_5 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_5}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_10/Uart_ETH_util_vector_logic_2_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_10 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_10}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_9/Uart_ETH_UART_TX_Extended_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_9 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_9}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_42/Uart_ETH_util_vector_logic_0_42.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_42 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_42}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_10/Uart_ETH_fifo_generator_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_10 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_10}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_9/Uart_ETH_UART_RX_Extended_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_9 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_9}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_9/Uart_ETH_util_vector_logic_2_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_9 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_9}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_8/Uart_ETH_UART_TX_Extended_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_8 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_8}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_41/Uart_ETH_util_vector_logic_0_41.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_41 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_41}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_9/Uart_ETH_fifo_generator_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_9 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_9}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_8/Uart_ETH_UART_RX_Extended_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_8 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_8}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_8/Uart_ETH_util_vector_logic_2_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_8 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_8}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_7/Uart_ETH_UART_TX_Extended_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_7 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_7}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_40/Uart_ETH_util_vector_logic_0_40.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_40 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_40}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_8/Uart_ETH_fifo_generator_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_8 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_8}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_7/Uart_ETH_UART_RX_Extended_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_7 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_7}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_7/Uart_ETH_util_vector_logic_2_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_7 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_7}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_6/Uart_ETH_UART_TX_Extended_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_6 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_6}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_39/Uart_ETH_util_vector_logic_0_39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_39 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_39}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_7/Uart_ETH_fifo_generator_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_7 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_7}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_6/Uart_ETH_UART_RX_Extended_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_6 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_6}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_14/Uart_ETH_util_vector_logic_2_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_14 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_14}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_13/Uart_ETH_UART_TX_Extended_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_13 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_13}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_46/Uart_ETH_util_vector_logic_0_46.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_46 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_46}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_14/Uart_ETH_fifo_generator_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_14 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_14}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_13/Uart_ETH_UART_RX_Extended_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_13 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_13}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_15/Uart_ETH_util_vector_logic_2_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_15 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_15}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_14/Uart_ETH_UART_TX_Extended_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_14 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_14}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_47/Uart_ETH_util_vector_logic_0_47.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_47 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_47}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_16/Uart_ETH_fifo_generator_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_16 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_16}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_14/Uart_ETH_UART_RX_Extended_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_14 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_14}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_16/Uart_ETH_util_vector_logic_2_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_16 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_16}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_15/Uart_ETH_UART_TX_Extended_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_15 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_15}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_48/Uart_ETH_util_vector_logic_0_48.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_48 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_48}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_30/Uart_ETH_fifo_generator_0_30.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_30 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_30}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_15/Uart_ETH_UART_RX_Extended_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_15 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_15}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_13/Uart_ETH_util_vector_logic_2_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_13 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_13}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_12/Uart_ETH_UART_TX_Extended_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_12 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_12}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_45/Uart_ETH_util_vector_logic_0_45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_45 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_45}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_13/Uart_ETH_fifo_generator_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_13 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_13}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_12/Uart_ETH_UART_RX_Extended_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_12 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_12}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_12/Uart_ETH_util_vector_logic_2_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_12 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_12}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_11/Uart_ETH_UART_TX_Extended_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_11 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_11}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_44/Uart_ETH_util_vector_logic_0_44.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_44 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_44}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_12/Uart_ETH_fifo_generator_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_12 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_12}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_11/Uart_ETH_UART_RX_Extended_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_11 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_11}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_18/Uart_ETH_util_vector_logic_2_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_18 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_18}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_17/Uart_ETH_UART_TX_Extended_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_17 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_17}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_50/Uart_ETH_util_vector_logic_0_50.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_50 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_50}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_32/Uart_ETH_fifo_generator_0_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_32 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_32}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_17/Uart_ETH_UART_RX_Extended_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_17 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_17}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_17/Uart_ETH_util_vector_logic_2_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_17 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_17}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_16/Uart_ETH_UART_TX_Extended_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_16 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_16}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_49/Uart_ETH_util_vector_logic_0_49.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_49 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_49}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_31/Uart_ETH_fifo_generator_0_31.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_31 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_31}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_16/Uart_ETH_UART_RX_Extended_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_16 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_16}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_20/Uart_ETH_util_vector_logic_2_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_20 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_20}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_19/Uart_ETH_UART_TX_Extended_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_19 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_19}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_52/Uart_ETH_util_vector_logic_0_52.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_52 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_52}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_34/Uart_ETH_fifo_generator_0_34.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_34 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_34}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_19/Uart_ETH_UART_RX_Extended_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_19 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_19}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_2_19/Uart_ETH_util_vector_logic_2_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_2_19 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_2_19}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Extended_0_18/Uart_ETH_UART_TX_Extended_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Extended_0_18 || ORIG_REF_NAME==Uart_ETH_UART_TX_Extended_0_18}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_51/Uart_ETH_util_vector_logic_0_51.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_51 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_51}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_33/Uart_ETH_fifo_generator_0_33.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_33 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_33}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Extended_0_18/Uart_ETH_UART_RX_Extended_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Extended_0_18 || ORIG_REF_NAME==Uart_ETH_UART_RX_Extended_0_18}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_0_1/Uart_ETH_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_0_1 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_0_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_fifo_generator_0_0/Uart_ETH_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_fifo_generator_0_0 || ORIG_REF_NAME==Uart_ETH_fifo_generator_0_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_RX_Without_Baud_1_0/Uart_ETH_UART_RX_Without_Baud_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_RX_Without_Baud_1_0 || ORIG_REF_NAME==Uart_ETH_UART_RX_Without_Baud_1_0}]

# IP: bd/Uart_ETH/ip/Uart_ETH_util_vector_logic_14_1/Uart_ETH_util_vector_logic_14_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_util_vector_logic_14_1 || ORIG_REF_NAME==Uart_ETH_util_vector_logic_14_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_UART_TX_Without_Baud_14_1/Uart_ETH_UART_TX_Without_Baud_14_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_UART_TX_Without_Baud_14_1 || ORIG_REF_NAME==Uart_ETH_UART_TX_Without_Baud_14_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_IO_In_Out_Switcher_0_1/Uart_ETH_IO_In_Out_Switcher_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_IO_In_Out_Switcher_0_1 || ORIG_REF_NAME==Uart_ETH_IO_In_Out_Switcher_0_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlconstant_0_2/Uart_ETH_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlconstant_0_2 || ORIG_REF_NAME==Uart_ETH_xlconstant_0_2}]

# IP: bd/Uart_ETH/ip/Uart_ETH_xlslice_KeyPad_1/Uart_ETH_xlslice_KeyPad_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_xlslice_KeyPad_1 || ORIG_REF_NAME==Uart_ETH_xlslice_KeyPad_1}]

# IP: bd/Uart_ETH/ip/Uart_ETH_auto_pc_0/Uart_ETH_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_ETH_auto_pc_0 || ORIG_REF_NAME==Uart_ETH_auto_pc_0}]

# XDC: bd/Uart_ETH/Uart_ETH_ooc.xdc
