// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x80 ~
// 0xff : Memory 'a' (32 * 32b)
//        Word n : bit [31:0] - a[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XUART_CONFIG_REGISTER_AXILITES_ADDR_A_BASE 0x80
#define XUART_CONFIG_REGISTER_AXILITES_ADDR_A_HIGH 0xff
#define XUART_CONFIG_REGISTER_AXILITES_WIDTH_A     32
#define XUART_CONFIG_REGISTER_AXILITES_DEPTH_A     32

