// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XALL_DATA_SENDER_H
#define XALL_DATA_SENDER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xall_data_sender_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XAll_data_sender_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XAll_data_sender;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAll_data_sender_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAll_data_sender_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAll_data_sender_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAll_data_sender_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAll_data_sender_Initialize(XAll_data_sender *InstancePtr, u16 DeviceId);
XAll_data_sender_Config* XAll_data_sender_LookupConfig(u16 DeviceId);
int XAll_data_sender_CfgInitialize(XAll_data_sender *InstancePtr, XAll_data_sender_Config *ConfigPtr);
#else
int XAll_data_sender_Initialize(XAll_data_sender *InstancePtr, const char* InstanceName);
int XAll_data_sender_Release(XAll_data_sender *InstancePtr);
#endif


u32 XAll_data_sender_Get_a_BaseAddress(XAll_data_sender *InstancePtr);
u32 XAll_data_sender_Get_a_HighAddress(XAll_data_sender *InstancePtr);
u32 XAll_data_sender_Get_a_TotalBytes(XAll_data_sender *InstancePtr);
u32 XAll_data_sender_Get_a_BitWidth(XAll_data_sender *InstancePtr);
u32 XAll_data_sender_Get_a_Depth(XAll_data_sender *InstancePtr);
u32 XAll_data_sender_Write_a_Words(XAll_data_sender *InstancePtr, int offset, int *data, int length);
u32 XAll_data_sender_Read_a_Words(XAll_data_sender *InstancePtr, int offset, int *data, int length);
u32 XAll_data_sender_Write_a_Bytes(XAll_data_sender *InstancePtr, int offset, char *data, int length);
u32 XAll_data_sender_Read_a_Bytes(XAll_data_sender *InstancePtr, int offset, char *data, int length);

#ifdef __cplusplus
}
#endif

#endif
