# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    e:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/ipshared/6eb1/hdl
    e:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/ipshared/7e3a/hdl
    e:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/ipshared/39ca/hdl/verilog
    e:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/ipshared/f80f/hdl/verilog
    e:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/ipshared/9c7f
    e:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/ipshared/d618/hdl/verilog
    e:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/ipshared/f9cc/hdl/verilog
    e:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/ipshared/ecd6/hdl/verilog
    e:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/ipshared/ce23/hdl/verilog
  } {
      C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_vhdl -lib xil_defaultlib {
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_processing_system7_0_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_axi_gpio_LED_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_axi_gpio_SW_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xbar_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_AllDataMover_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_smartconnect_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_All_Data_Sender_0_4_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_clk_wiz_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_clk_wiz_1_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_rst_ps7_0_100M_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_rst_ps7_0_100M_2_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_Config_Register_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_Extract_UART_Features_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_2_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_baudrate_gen_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_1_14_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_10_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_0_3_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_2_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_3_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_4_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_5_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_6_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_7_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_8_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_9_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_10_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_11_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_12_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_DataMuxOut4Bit_1_13_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_4_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_15_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_PISO_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_LED_Tester_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_14_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlconcat_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_Register_8_Input_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_Register_8_Input_1_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_Register_8_Input_Rx1_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_Register_8_Input_Rx2_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_LED_Sample_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_LED_Sample_0_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_LED_Sample_1_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_LED_Sample_1_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_Tick_Timer_General_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_0_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_KeyPad_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_Tick_Timer_General_0_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_LCD_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_LCD1_2_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_LCD_RS_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_LCD1_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_LCD_RS_2_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_LCD_RS_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_LCD1_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_Counter_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlconstant_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_18_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlconcat_0_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlconstant_0_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_xlslice_LCD_RW_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_19_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_20_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_21_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_22_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_23_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_24_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_25_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_26_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_27_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_28_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_29_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_30_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_11_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_11_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_12_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_12_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_12_2_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_12_3_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_12_4_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_12_5_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_12_6_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_12_7_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_21_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_21_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_21_2_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_21_3_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_21_4_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_21_5_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_21_6_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_21_7_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_21_8_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_30_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_37_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_3_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Without_Baud_1_17_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_14_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Without_Baud_14_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_ila_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_5_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_4_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_36_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_5_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_4_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_6_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_5_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_38_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_6_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_5_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_10_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_9_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_42_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_10_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_9_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_9_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_8_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_41_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_9_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_8_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_8_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_7_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_40_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_8_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_7_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_7_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_6_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_39_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_7_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_6_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_14_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_13_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_46_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_14_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_13_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_15_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_14_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_47_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_16_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_14_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_16_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_15_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_48_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_30_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_15_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_13_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_12_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_45_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_13_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_12_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_12_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_11_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_44_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_12_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_11_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_18_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_17_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_50_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_32_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_17_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_17_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_16_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_49_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_31_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_16_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_20_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_19_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_52_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_34_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_19_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_2_19_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Extended_0_18_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_51_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_33_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Extended_0_18_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_ila_0_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_0_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_fifo_generator_0_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_RX_Without_Baud_1_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_util_vector_logic_14_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_UART_TX_Without_Baud_14_1_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/realtime/Uart_ETH_auto_pc_0_stub.vhdl
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/hdl/Uart_ETH.vhd
      E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/UART2ETH.srcs/sources_1/bd/Uart_ETH/hdl/Uart_ETH_wrapper.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Uart_ETH_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "E:/ETH2SER/SoftwareProjects/UART2ETH970431_Master_Slave/.Xil/Vivado-5652-AVACO-PC2/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
