// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x100 ~
// 0x1ff : Memory 'a' (36 * 32b)
//         Word n : bit [31:0] - a[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XALL_DATA_SENDER_AXILITES_ADDR_A_BASE 0x100
#define XALL_DATA_SENDER_AXILITES_ADDR_A_HIGH 0x1ff
#define XALL_DATA_SENDER_AXILITES_WIDTH_A     32
#define XALL_DATA_SENDER_AXILITES_DEPTH_A     36

